media:
  input: "public/images"
  output: "/images"

collections:
  - name: "블로그 글 관리"
    id: "blog"
    path: "src/content/blog"
    format: "md"
    fields:
      - name: "제목"
        id: "title"
        type: "string"
        required: true
      - name: "요약 문구"
        id: "description"
        type: "string"
        required: true
      - name: "발행 날짜"
        id: "pubDate"
        type: "date"
        required: true
      - name: "본문 내용"
        id: "body"
        type: "rich-text"
        required: true
