collections:
  - name: "블로그 글 관리"
    id: "blog"
    path: "src/content/blog"
    fields:
      - { name: "제목", id: "title", type: "string" }
      - { name: "요약", id: "description", type: "string" }
      - { name: "날짜", id: "pubDate", type: "date" }
      - { name: "본문", id: "body", type: "rich-text" }
